OrderingSystemProject/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using OrderingSystemProject.Models;
using OrderingSystemProject.Services;
using OrderingSystemProject.Utilities;
using OrderingSystemProject.ViewModels;

namespace OrderingSystemProject.Controllers;

public class RestaurantController : Controller
{
    private readonly ITablesService _tablesService;
    private readonly IOrderService _ordersService;

    public RestaurantController(ITablesService tablesService, IOrderService ordersService)
    {
        _tablesService = tablesService;
        _ordersService = ordersService;
    }
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Overview()
    {
        EmployeeType? userRole = Authorization.GetUserRole(HttpContext);

        // check if user is logged in and has correct role
        if (userRole != EmployeeType.Waiter && userRole != EmployeeType.Manager) return RedirectToAction("Login", "Employees");

        try
        {
            // get all tables with and with no order
            List<Table> tables = _tablesService.GetAllTables();
            List<Order> activeOrders = _ordersService.GetActiveOrders();

            Dictionary<int, Order> ordersDictionary = new Dictionary<int, Order>();
            foreach (Order order in activeOrders)
            {
                ordersDictionary[order.TableId] = order;
            }
            // create view model
            RestaurantOverviewViewModel viewModel = new RestaurantOverviewViewModel(tables, ordersDictionary);

            // return view with view model
            return View(viewModel);
        }
        catch (Exception ex)
        {
            ViewData["Exception"] = "An error occurred. Please try again." + ex.Message;
            // return empty view model in case of error
            return View(new RestaurantOverviewViewModel());
        }
    }

    [HttpPost]
    public IActionResult Overview(Table table)
    {
        return View();
    }

    [HttpGet]
    public IActionResult RefreshOverview()
    {
        try
        {
            // set success message
            TempData["SuccessMessage"] = "Tables refreshed at " + DateTime.Now.ToString("HH:mm:ss");
        
            // refreshing by redirecting to Overview 
            return RedirectToAction("Overview");
        }
        catch (Exception ex)
        {
            // set error message
            TempData["Exception"] = "Error refreshing tables: " + ex.Message;
            return RedirectToAction("Overview");
        }
    }
    
    [HttpGet]
    public IActionResult FreeTable(int tableId)
    {
        bool isStatusChanged = _tablesService.ChangeTableStatus(tableId, TableStatus.Available);
    
        if (!isStatusChanged)
        {
            TempData["ErrorMessage"] = "Cannot change table status - table has active orders";
            return RedirectToAction("Overview");
        }
        return RedirectToAction("RefreshOverview");
    }

    [HttpGet]
    public IActionResult OccupyTable(int tableId)
    {
        bool isStatusChanged = _tablesService.ChangeTableStatus(tableId, TableStatus.Occupied);
        
        if (!isStatusChanged)
        {
            TempData["ErrorMessage"] = "Cannot change table status";
            return RedirectToAction("Overview"); 
        }
        return RedirectToAction("RefreshOverview");
    }
    
    [HttpGet]
    public IActionResult MarkAsServed(int orderId, string itemType)
    {
        try
        {
            if (_ordersService.MarkOrderAsServed(orderId, itemType))
                TempData["SuccessMessage"] = $"{itemType} marked as served successfully!";
            else
                TempData["ErrorMessage"] = $"Could not mark {itemType} as served.";
        }
        catch (Exception ex)
        {
            TempData["ErrorMessage"] = "Error updating order status: " + ex.Message;
        }
        return RedirectToAction("RefreshOverview");
    }
}

OrderingSystemProject/Controllers/WaiterController.cs
using Microsoft.AspNetCore.Mvc;
using OrderingSystemProject.Models;
using OrderingSystemProject.Services;
using OrderingSystemProject.Utilities;
using OrderingSystemProject.ViewModels;

namespace OrderingSystemProject.Controllers
{
    public class WaiterController : Controller
    {
        private readonly IMenuItemService _menuItemService;
        private readonly ITablesService _tablesService;
        private WaiterViewModel _waiterViewModel;
        private readonly IOrderService _orderService;

        public WaiterController(IMenuItemService menuItemService, ITablesService tablesService, IOrderService orderService)
        {
            _menuItemService = menuItemService;
            _tablesService = tablesService;
            _orderService = orderService;
        }

        [HttpGet("Waiter/Index/{tableId}")]
        public IActionResult Index(int? tableId)
        {
            if (!Authenticate()) return RedirectToAction("Login", "Employees");

            try
            {
                if (tableId == null)            // No table selected, redirect to restaurant overview.
                {
                    return RedirectToAction("Overview", "Restaurant");
                }
                var table = _tablesService.GetTableByNumber((int)tableId);
                if (table == null)
                {
                    throw new Exception("Invalid Table ID");
                }

                // Build view model with current table, full menu and cart 
                var model = new WaiterViewModel
                {
                    Table = _tablesService.GetTableByNumber((int)tableId),
                    MenuItems = _menuItemService.GetAll(),
                    Cart = _menuItemService.GetCart(),
                };
              
                return View(model);
            }
            catch (Exception ex)
            {
                ViewData["Exception"] = ex.Message;
                return RedirectToAction("Overview", "Restaurant");
            }
        }

        [HttpPost]
        public IActionResult AddItem(int itemId, int tableId)
        {
            if (!Authenticate()) return RedirectToAction("Login", "Employees");

            try
            {
                // Add item to cart using service.
                _menuItemService.AddItem(itemId);
                var addedItem = _menuItemService.GetById(itemId);

                TempData["SuccessMessage"] = $"Item {addedItem.Name} was added to the Order!";
                return RedirectToAction("Index", new { tableId });
            }
            catch (Exception e)
            {
                ViewData["Exception"] = $"Error with adding item to the Order: {e.Message}";
                return RedirectToAction("Index", new { tableId });
            }
        }


        [HttpPost]
        public IActionResult IncreaseQuantity(int itemId, int tableId)
        {
            if (!Authenticate()) return RedirectToAction("Login", "Employees");

            try
            {
                _menuItemService.IncreaseQuantity(itemId);

                var increaseQ = _menuItemService.GetById(itemId);
                TempData["SuccessMessage"] = $"Amount of '{increaseQ.Name}' was increased by 1";

                return RedirectToAction("Index", new { tableId });
            }
            catch (Exception e)
            {
                TempData["Exception"] = $"Error with increasing amount: {e.Message}";

                return RedirectToAction("Index", new { tableId });
            }
        }

        [HttpPost]
        public IActionResult DecreaseQuantity(int itemId, int tableId)
        {
            if (!Authenticate()) return RedirectToAction("Login", "Employees");

            try
            {
                _menuItemService.DecreaseQuantity(itemId);

                var decreaseQ = _menuItemService.GetById(itemId);
                TempData["SuccessMessage"] = $"Amount of '{decreaseQ.Name}' was deacresed by 1";

                return RedirectToAction("Index", new { tableId });
            }
            catch (Exception e)
            {
                TempData["Exception"] = $"Error with decreasing amount: {e.Message}";

                return RedirectToAction("Index", new { tableId });
            }
        }


        [HttpPost]
        public IActionResult RemoveItem(int itemId, int tableId)
        {
            if (!Authenticate()) return RedirectToAction("Login", "Employees");

            try
            {
                _menuItemService.RemoveItem(itemId);

                var removedItem = _menuItemService.GetById(itemId);
                TempData["SuccessMessage"] = $"Item '{removedItem.Name}' was removed!";

                return RedirectToAction("Index", new { tableId });
            }
            catch (Exception e)
            {
                TempData["Exception"] = $"Error with removing item: {e.Message}";

                return RedirectToAction("Index", new { tableId });
            }
        }

        [HttpPost]
        public IActionResult UpdateComment(int itemId, string comment, int tableId)
        {
            if (!Authenticate()) return RedirectToAction("Login", "Employees");

            try
            {
                _menuItemService.UpdateComment(itemId, comment);
                var updatedItem = _menuItemService.GetById(itemId);

                TempData["SuccessMessage"] = $"Comment '{comment}' was added to {updatedItem.Name}!";
                return RedirectToAction("Index", new { tableId });
            }
            catch (Exception e)
            {
                TempData["Exception"] = $"Error updating comment: {e.Message}";

                return RedirectToAction("Index", new { tableId });
            }
        }

        [HttpPost]
        public IActionResult ClearOrder(int tableId)
        {
            if (!Authenticate()) return RedirectToAction("Login", "Employees");

            try
            {
                // Clear all items from cart
                _menuItemService.CancelOrder();

                TempData["SuccessMessage"] = $"Order was Cancelled!";
                return RedirectToAction("Index", new { tableId });
            }
            catch (Exception e)
            {
                TempData["Exception"] = $"Error with Order canceling: {e.Message}";

                return RedirectToAction("Index", new { tableId });
            }
        }

        [HttpGet]
        public IActionResult ReviewOrder(int tableId)
        {
            if (!Authenticate()) return RedirectToAction("Login", "Employees");

            try
            {
                // Load full cart and table info for review
                var model = new WaiterViewModel
                {
                    Table = _tablesService.GetTableByNumber(tableId),
                    MenuItems = _menuItemService.GetAll(),
                    Cart = _menuItemService.GetCart()
                };

                return View(model);
            }
            catch (Exception e)
            {
                TempData["Exception"] = $"Error with Order Review: {e.Message}";

                return View();
            }
        }

        [HttpPost]
        public IActionResult SendToKitchen(int tableId)
        {
            if (!Authenticate()) return RedirectToAction("Login", "Employees");

            try
            {
                // Get current cart items
                var orderedItems = _menuItemService.GetCart();

                // Create the order and persist it via service
                var order = _orderService.CreateOrder(tableId, orderedItems);

                // Cleaning cart after sending 
                _menuItemService.CancelOrder();

                TempData["SuccessMessage"] = $"Order №{order.OrderId} was successfully sent to the Kitchen!";
                return RedirectToAction("ReviewOrder", new { tableId });
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = $"Order Error: {e.Message}";
                return RedirectToAction("ReviewOrder", new { tableId });
            }
        }
        
        public IActionResult Filter(
            CardFilterType cardFilterType,
            CategoryFilterType categoryFilterType, 
            int tableId
        )
        {
            if (!Authenticate()) return RedirectToAction("Login", "Employees");

            try
            {
                // Filter menu items based on category and card 
                List<MenuItem> menuItems = _menuItemService.Filter(categoryFilterType, cardFilterType);

                var model = new WaiterViewModel
                {
                    CardFilter = cardFilterType,
                    CategoryFilter = categoryFilterType,
                    Table = _tablesService.GetTableByNumber((int)tableId),
                    MenuItems = menuItems,
                    Cart = _menuItemService.GetCart(),
                };

                return View(nameof(Index), model);
            }
            catch (Exception e)
            {
                ViewData["Exception"] = $"Exception occured: {e.Message}";
                return View();
            }
        }

        // Checks logged-in user 
        private bool Authenticate()
        {
            var user_role = Authorization.GetUserRole(this.HttpContext);

            if (user_role != null && (user_role == EmployeeType.Waiter || user_role == EmployeeType.Manager)) return true;

            return false;
        }
    }
}

OrderingSystemProject/Views/Restaurant/Overview.cshtml
@model OrderingSystemProject.ViewModels.RestaurantOverviewViewModel

@{
    ViewData["Title"] = "Restaurant Overview";
}

<h4 class="text-center mb-4">Restaurant Overview</h4>

<partial name="_ErrorMessage" />

<!-- Display success message -->
<partial name="_SuccessMessage"/>

<!-- Refresh overview -->
<div class="mb-4">
    <a asp-controller="Restaurant" asp-action="RefreshOverview" class="btn btn-refresh">Refresh Tables</a>
</div>

<div class="row row-cols-1 row-cols-md-5 g-4">
    @foreach (Table table in Model.Tables)
    {
        // get order for this table
        Order? order = Model.GetActiveOrderForTable(table.TableId);
        
        string cardColorClass;
        string tableStatusText;
        
        if (table.Status == TableStatus.Available)
        {
            cardColorClass = "table-available";
            tableStatusText = "Available";
        }
        else if (table.Status == TableStatus.Occupied)
        {
            cardColorClass = "table-occupied";
            tableStatusText = "Occupied";
        }
        else
        {
            cardColorClass = "table-unknown";
            tableStatusText = "Unknown";
        }

        <!-- Table overview card -->
        <div class="col px-1"> 
            <div class="card m-1" style="width: 100%;">
                <div class="card-header text-center table-card-dropdown dropdown">
                    <!-- Table number and dropdown button -->
                    <button class="table-dropdown-btn" type="button" data-bs-toggle="dropdown">Table @table.TableNumber</button>
                    <ul class="dropdown-menu">
                        @if (table.Status == TableStatus.Available)
                        {
                            <li>
                                <a class="dropdown-item occupy-action" asp-controller="Restaurant" asp-action="OccupyTable" asp-route-tableId="@table.TableId">Occupy Table</a>
                            </li>
                        }
                        else if (table.Status == TableStatus.Occupied)
                        {
                            <li>
                                <a class="dropdown-item free-action" asp-controller="Restaurant" asp-action="FreeTable" asp-route-tableId="@table.TableId">Free Table</a>
                            </li>
                        }
                    </ul>
                </div>
                <!-- Always show "Bill" if there's an order -->
                @if (order != null)
                {
                    <a href="/Payment/Details/@order.OrderId" class="bill-button-table">Bill</a>
                    //<a asp-controller="Payment" asp-action="Details" asp-route-orderId="@order.OrderId" class="bill-button-table">Bill</a>
                }

                <!-- Show "Select" only if the table is available -->
                @if (table.Status == TableStatus.Available)
                {
                    <a href="/Waiter/Index/@table.TableId" class="bill-button-table">Select</a>
                    //<a asp-controller="Waiter" asp-action="Index" asp-route-tableId="@table.TableId" class="btn btn-primary mt-1">Select</a>
                }
                <!-- Card body with Order info -->
                <div class="card-body @cardColorClass" style="height: 150px;">
                    <p class="card-text text-center">@tableStatusText</p>
                    <!-- Food order status info -->
                    @if (order != null)
                    {
                        @if (order.FoodStatus != null)
                        {
                            string foodStatusText = "";
                            if (order.FoodStatus == OrderItemStatus.NewItem) foodStatusText = "New";
                            else if (order.FoodStatus == OrderItemStatus.Preparing) foodStatusText = "Preparing";  
                            else if (order.FoodStatus == OrderItemStatus.Ready) foodStatusText = "Ready";
                            else if (order.FoodStatus == OrderItemStatus.Served) foodStatusText = "Served";
                            <!-- Change food status if the order is ready(dropdown menu) -->
                            <div>
                                Food: 
                                @if (order.FoodStatus == OrderItemStatus.Ready)
                                {
                                    <div class="dropdown d-inline">
                                        <button class="status-dropdown-btn" type="button" data-bs-toggle="dropdown">@foodStatusText ▼</button>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a class="dropdown-item" asp-controller="Restaurant" asp-action="MarkAsServed" asp-route-orderId="@order.OrderId" asp-route-itemType="food">Mark as Served</a>
                                            </li>
                                        </ul>
                                    </div>
                                }
                                else
                                { 
                                    @foodStatusText
                                }
                            </div>
                        }
                        <!-- Drinks order status info -->
                        @if (order.DrinkStatus != null)
                        {
                            string drinkStatusText = "";
                            if (order.DrinkStatus == OrderItemStatus.NewItem) drinkStatusText = "New";
                            else if (order.DrinkStatus == OrderItemStatus.Preparing) drinkStatusText = "Preparing";  
                            else if (order.DrinkStatus == OrderItemStatus.Ready) drinkStatusText = "Ready";
                            else if (order.DrinkStatus == OrderItemStatus.Served) drinkStatusText = "Served";
                            <!-- Change drinks status if the order is ready(dropdown menu) -->
                            <div>
                                Drinks: 
                                @if (order.DrinkStatus == OrderItemStatus.Ready)
                                {
                                    <div class="dropdown d-inline">
                                        <button class="status-dropdown-btn" type="button" data-bs-toggle="dropdown">@drinkStatusText ▼</button>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a class="dropdown-item" asp-controller="Restaurant" asp-action="MarkAsServed" asp-route-orderId="@order.OrderId" asp-route-itemType="drink">Mark as Served</a>
                                            </li>
                                        </ul>
                                    </div>
                                }
                                else
                                {
                                   @drinkStatusText
                                }
                            </div>
                        }
                        <div>Time: @order.OrderTime.ToString("HH:mm")</div>
                    }
                    else
                    {
                        <div>No active order</div>
                    }
                </div>
            </div>
        </div>
    }
</div> 